# App Settings
spring:
  application:
    name: discovery-service

server:
  port: 8761

# Eureka Settings
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0