# App settings
spring:
  config:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/speedment/eventsourcing-examples
          searchPaths: '{application}'

server:
  port: 8888